{% set name = "pyiron_continuum" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_continuum-{{ version }}.tar.gz
  sha256: 22902232c75255ba833df3573f06f964a834e635b449506a15b89a7a7497dd31

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - matplotlib-base >=3.8.0
    - numpy >=1.26.0
    - pyiron_base >=0.6.7
    - scipy >=1.11.3
    - sympy >=1.12

test:
  imports:
    - pyiron_continuum
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_continuum
  summary: Repository for user-generated plugins to the pyiron IDE.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
    - niklassiemer
