{% set name = "pyiron_continuum" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_continuum-{{ version }}.tar.gz
  sha256: f6d4cf778e177ce1c062ef5c1e0050cb3f5ce6d2c5f33257f3f27a1cbd5284a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.8.3
    - numpy >=1.26.4
    - pyiron_base >=0.7.11
    - scipy >=1.12.0
    - sympy >=1.12
    - python-blosc2  # required by table

test:
  imports:
    - pyiron_continuum
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyiron_continuum
  summary: Repository for user-generated plugins to the pyiron IDE.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
    - niklassiemer
