{% set name = "pyiron_continuum" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_continuum-{{ version }}.tar.gz
  sha256: 7f605be982a52249a29396c623d425c9bb58819fe10cfe6160a0b17d5ed61a74

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - matplotlib-base >=3.4.2
    - numpy >=1.21.0
    - pyiron_base >=0.2.19
    - python >=3.5

test:
  imports:
    - pyiron_continuum
    - pyiron_continuum.damask
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_continuum
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Additional modules for the pyiron IDE supporting continuum dynamics
  description: |
    additional modules for the pyiron IDE supporting continuum dynamics
  doc_url: https://github.com/pyiron/pyiron_continuum
  dev_url: https://github.com/pyiron/pyiron_continuum

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - muh-hassani
    - niklassiemer
