{% set name = "pyiron_continuum" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_continuum-{{ version }}.tar.gz
  sha256: c5e26992cc4f8315e2eec595ceebcf28e4e6723c3bf84f9088c153543e7ef71c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - matplotlib-base >=3.8.2
    - numpy >=1.26.2
    - pyiron_base >=0.6.9
    - scipy >=1.11.4
    - sympy >=1.12
    - python-blosc2  # required by table

test:
  imports:
    - pyiron_continuum
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_continuum
  summary: Repository for user-generated plugins to the pyiron IDE.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
    - niklassiemer
