{% set name = "pyiron_continuum" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_continuum-{{ version }}.tar.gz
  sha256: 22902232c75255ba833df3573f06f964a834e635b449506a15b89a7a7497dd31

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - matplotlib-base >=3.8.0
    - numpy >=1.26.0
    - pyiron_base >=0.6.8
    - python >=3.5
    - sympy >=1.12
    - scipy >=1.11.3

test:
  imports:
    - pyiron_continuum
    - pyiron_continuum.damask
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_continuum
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Additional modules for the pyiron IDE supporting continuum dynamics
  description: |
    additional modules for the pyiron IDE supporting continuum dynamics
  doc_url: https://github.com/pyiron/pyiron_continuum
  dev_url: https://github.com/pyiron/pyiron_continuum

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
    - niklassiemer
