{% set name = "pyiron_continuum" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_continuum-{{ version }}.tar.gz
  sha256: 6aa27897049860afba28f18f7d2d51a3bf9b7a470d989a55df79d55eb4ba7845

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
  run:
    - pyiron_snippets >=0.1.4
    - python >=3.5
    - matplotlib-base >=3.9.2
    - numpy >=1.26.4
    - pyiron_base >=0.9.12
    - scipy >=1.14.1
    - sympy >=1.13.2
    - python-blosc2  # required by table

test:
  imports:
    - pyiron_continuum
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_continuum
  summary: Repository for user-generated plugins to the pyiron IDE.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - jan-janssen
    - pmrv
    - srmnitc
    - niklassiemer
